package client.request;

public enum RequestType {
    AUTHENTICATE,
    CREATE_GAME,
    UPDATE_GAME,
    PLAY_CARD,
    GAME_LIST,
    GET_PLAYERS, JOIN_GAME, EXIT_GAME, START_GAME, PLAY_NINJA, EMOJI, UPDATE_PLAYER_LIST
}
